Update multi-openwrt.yml

diff --git a/.github/workflows/multi-openwrt.yml b/.github/workflows/multi-openwrt.yml
--- a/.github/workflows/multi-openwrt.yml
+++ b/.github/workflows/multi-openwrt.yml
@@ -718,9 +718,9 @@ jobs:
         if: env.Release == 'true' && !failure() && !cancelled() && env.PLUGINver == 'true'
         #  tar zcvf RELEASE/$openclash_ssrplus_passwall_BIN.tar.gz openwrt/bin/ || echo "$NAME is no directory BIN"
         run: |
-        tar zcvf RELEASE/$openclash_ssrplus_passwall_BIN.tar.gz --exclude=openwrt/bin/targets/*/*/*squashfs-factory.bin  --exclude=openwrt/bin/targets/*/*/*squashfs-sysupgrade.bin openwrt/bin/ || echo "$NAME is no directory BIN"
-        tar zcvf RELEASE/$openclash_ssrplus_passwall_FACTORY.tar.gz openwrt/bin/targets/*/*/*squashfs-factory.bin || echo "$NAME is no factory.bin"
-        tar zcvf RELEASE/$openclash_ssrplus_passwall_SYSUPGRADE.tar.gz openwrt/bin/targets/*/*/*squashfs-sysupgrade.bin || echo "ERROR: $NAME is no sysupgrade"
+          tar zcvf RELEASE/$openclash_ssrplus_passwall_BIN.tar.gz --exclude=openwrt/bin/targets/*/*/*squashfs-factory.bin  --exclude=openwrt/bin/targets/*/*/*squashfs-sysupgrade.bin openwrt/bin/ || echo "$NAME is no directory BIN"
+          tar zcvf RELEASE/$openclash_ssrplus_passwall_FACTORY.tar.gz openwrt/bin/targets/*/*/*squashfs-factory.bin || echo "$NAME is no factory.bin"
+          tar zcvf RELEASE/$openclash_ssrplus_passwall_SYSUPGRADE.tar.gz openwrt/bin/targets/*/*/*squashfs-sysupgrade.bin || echo "ERROR: $NAME is no sysupgrade"
       
       
       - name: 1.UPload1 test
@@ -737,18 +737,19 @@ jobs:
       - name: 1.UPload1 start
         id: UPload1_start
         if: env.Release == 'true' && steps.UPload1_start.outputs.status == 'success' && !failure() && !cancelled() 
-		  logname=$(date +"%Y.%m.%d-%H:%M")
-		  rclone sync -P --transfers=4 --ignore-errors --log-file=/onedrive5g/log/360T7_backup_${logname}.log -v RELEASE/* one:360T7/ && echo '上传成功' 
-		  up_status=`cat /onedrive5g/log/log`
-		  echo "up_status: $up_status"
+        run: |
+          logname=$(date +"%Y.%m.%d-%H:%M")
+          rclone sync -P --transfers=4 --ignore-errors --log-file=/onedrive5g/log/360T7_backup_${logname}.log -v RELEASE/* one:360T7/ && echo '上传成功' 
+          up_status=`cat /onedrive5g/log/log`
+          echo "up_status: $up_status"
 
       - name: 1.Download
-	    if: env.Release == 'true'  && !failure() && !cancelled() 
+        if: env.Release == 'true'  && !failure() && !cancelled()
         run: |
-		  rclone sync -P --transfers=4 --ignore-errors -v /onedrive5g/360T7/* RELEASE/ && echo '同步至本地成功' 
-		  echo "0" >  /onedrive5g/log/log 
-		  up_status=`cat /onedrive5g/log/log`
-		  echo "up_status: $up_status"
+	  rclone sync -P --transfers=4 --ignore-errors -v /onedrive5g/360T7/* RELEASE/ && echo '同步至本地成功' 
+	  echo "0" >  /onedrive5g/log/log 
+	  up_status=`cat /onedrive5g/log/log`
+	  echo "up_status: $up_status"
       
 	  # 如果下载过程或上传过程失败 log=0
       - name: 1.UPload Download Failure
